create sequence seq_configuracao_fiscal start with 1;

create table configuracao_fiscal (
	id						bigint not null constraint configuracao_fiscal_pkey primary key,
	uf_origem_id 			bigint NOT NULL,
	pais_destino_id			bigint NOT NULL,
	uf_destino_id			bigint NOT NULL,
	entrada_saida			varchar(10) NOT NULL,
	data_inicio_vigencia 	date NOT NULL,
	data_final_vigencia 	date NOT NULL,	
	grupo_tributacao_id 		bigint,
	cfop_id             		bigint,
	ncm_id              		bigint,
	regime_tributario_id 		bigint,
	origem_id					bigint,
	operacao_interna_id			bigint,
	classificacao_operacao_id	bigint,
	item_id						bigint,
	user_create     		bigint 		 not null,
	date_create				timestamp with time zone 	 not null,
	user_update     		bigint,
	date_update				timestamp with time zone,
	CONSTRAINT configuracao_fiscal_uf_origem_id_foreign FOREIGN KEY (uf_origem_id) REFERENCES uf (id),
	CONSTRAINT configuracao_fiscal_pais_destino_id_foreign FOREIGN KEY (pais_destino_id) REFERENCES pais (id),
	CONSTRAINT configuracao_fiscal_uf_destino_id_foreign FOREIGN KEY (uf_destino_id) REFERENCES uf (id),
	CONSTRAINT configuracao_fiscal_grupo_tributacao_id_foreign FOREIGN KEY (grupo_tributacao_id) REFERENCES grupo_tributacao (id),
	CONSTRAINT configuracao_fiscal_cfop_id_foreign FOREIGN KEY (cfop_id) REFERENCES cfop (id),
	CONSTRAINT configuracao_fiscal_ncm_id_foreign FOREIGN KEY (ncm_id) REFERENCES ncm (id),
	CONSTRAINT configuracao_fiscal_regime_tributario_id_foreign FOREIGN KEY (regime_tributario_id) REFERENCES regime_tributario (id),
	CONSTRAINT configuracao_fiscal_origem_id_foreign FOREIGN KEY (origem_id) REFERENCES origem (id),
	CONSTRAINT configuracao_fiscal_operacao_interna_id_foreign FOREIGN KEY (operacao_interna_id) REFERENCES operacao_interna (id),
	CONSTRAINT configuracao_fiscal_classificacao_operacao_id_foreign FOREIGN KEY (classificacao_operacao_id) REFERENCES classificacao_operacao (id),
	CONSTRAINT configuracao_fiscal_item_id_foreign FOREIGN KEY (item_id) REFERENCES item (id)
);