create sequence seq_movimento_estoque start with 1;

create table movimento_estoque (
	id					bigint not null constraint movimento_estoque_pkey primary key,
	empresa_filial_id	bigint not null,
	local_estoque_id	bigint not null,
	grupo_contabil_id	bigint not null,
	item_id				bigint not null,
	operacao_interna_id	bigint not null,
	tipo_movimento_estoque 		varchar(2) not null,
	operacao_estoque_fisico 	varchar(2) not null,
	operacao_estoque_financeiro varchar(2) not null,
	calcula_custo_medio_saldo   boolean not null,
	data		 		date not null,
	documento			varchar(20) not null,
	entrada				boolean not null,
	quantidade			decimal(20,5) not null,
	custo_medio			decimal(20,10) not null,
	valor				decimal(15,2) not null,
	tipo_documento_estoque		varchar(2) not null,
	protocolo_documento			bigint not null,
	user_create     	bigint 		 not null,
	date_create			timestamp with time zone 	 not null,
	user_update     	bigint,
	date_update			timestamp with time zone,
	CONSTRAINT movimento_estoque_empresa_filial_id_foreign FOREIGN KEY (empresa_filial_id) REFERENCES empresa_filial (id),
	CONSTRAINT movimento_estoque_local_estoque_id_foreign FOREIGN KEY (local_estoque_id) REFERENCES local_estoque (id),
	CONSTRAINT movimento_estoque_grupo_contabil_id_foreign FOREIGN KEY (grupo_contabil_id) REFERENCES grupo_contabil (id),
	CONSTRAINT movimento_estoque_item_id_foreign FOREIGN KEY (item_id) REFERENCES item (id),
	CONSTRAINT movimento_estoque_operacao_interna_id_foreign FOREIGN KEY (operacao_interna_id) REFERENCES operacao_interna (id),
	CONSTRAINT movimento_estoque_tipo_movimento_estoque_foreign FOREIGN KEY (tipo_movimento_estoque) REFERENCES tipo_movimento_estoque (value),
	CONSTRAINT movimento_estoque_operacao_estoque_fisico_foreign FOREIGN KEY (operacao_estoque_fisico) REFERENCES operacao_estoque (value),
	CONSTRAINT movimento_estoque_operacao_estoque_financeiro_foreign FOREIGN KEY (operacao_estoque_financeiro) REFERENCES operacao_estoque (value),
	CONSTRAINT movimento_estoque_tipo_documento_estoque_foreign FOREIGN KEY (tipo_documento_estoque) REFERENCES tipo_documento_estoque (value)
);
