create table tipo_tributo (
	value				char(15) not null constraint tipo_tributo_pkey primary key,
	name				varchar(250) not null
);

insert into tipo_tributo values ('ICMS', 'ICMS');
insert into tipo_tributo values ('PIS', 'PIS');
insert into tipo_tributo values ('COFINS', 'COFINS');
insert into tipo_tributo values ('IPI', 'IPI');


create sequence seq_situacao_tributaria start with 1;

create table situacao_tributaria (
	id					bigint not null constraint situacao_tributaria_pkey primary key,
	codigo				integer not null,
	nome				varchar(2000) not null,
	tipo_tributo		varchar(80) not null,
	simples_nacional	      boolean not null,
	aliquota_zero   	      boolean not null,
	requer_mensagem_fiscal	  boolean not null,
	destaca_st_saida	      boolean not null,
	exige_aliquota_desonerada boolean not null,
	controla_imposto_retido   boolean not null,
	excluir_icms_base_calculo boolean not null,
	excluir_icms_bc_piscofins boolean not null,
	nao_excluir_icms_entrada  boolean not null,
	user_create     	bigint 		 not null,
	date_create			timestamp with time zone 	 not null,
	user_update     	bigint,
	date_update			timestamp with time zone
);

insert into situacao_tributaria (id, codigo, nome, tipo_tributo, simples_nacional, aliquota_zero, requer_mensagem_fiscal, destaca_st_saida, exige_aliquota_desonerada, 
                                 controla_imposto_retido, excluir_icms_base_calculo, excluir_icms_bc_piscofins, nao_excluir_icms_entrada, user_create, date_create, user_update, date_update) values
 (nextval('seq_situacao_tributaria'),0,'Tributada Integralmente', 'ICMS', false, false, false, false, false, false, false, true, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),10,'Tributada e com cobrança do ICMS por Substituição Tributária', 'ICMS', false, false, false, true, false, false, false, true, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),20,'Com redução na base de cálculo', 'ICMS', false, false, true, false, false, false, false, true, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),30,'Isenta ou não tributada e com cobrança do ICMS por Substituição Tributária', 'ICMS', false, true, false, true, true, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),40,'Isenta', 'ICMS', false, true, true, false, true, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),41,'Não Tributada', 'ICMS', false, false, false, false, false, false, true, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),50,'Suspensão', 'ICMS', false, true, true, false, true, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),51,'Diferimento', 'ICMS', false, true, true, false, true, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),60,'ICMS cobrado anteriormente por Substituição Tributária', 'ICMS', false, true, true, false, false, true, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),61,'Tributação Monofásica sobre Combustíveis cobrada anteriormente', 'ICMS', false, false, true, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),70,'Com redução de base de cálculo e cobrança do ICMS por Substituição Tributária', 'ICMS', false, false, true, true, false, false, false, true, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),90,'Outras', 'ICMS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),101,'Tributada pelo Simples Nacional com permissão de Crédito', 'ICMS', true, false, false, false, false, false, false, true, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),102,'Tributada pelo Simples Nacional sem permissão de Crédito', 'ICMS', true, false, false, false, false, false, false, true, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),103,'Isenção do ICMS no Simples Nacional para a faixa de Receita Bruta', 'ICMS', true, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),201,'Tributada pelo Simples Nacional com Permissão de Crédito e com Cobrança do ICMS por Substituição Tributária', 'ICMS', true, false, false, false, false, false, false, true, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),202,'Tributada pelo Simples Nacional sem Permissão de Crédito e com Cobrança do ICMS por Substituição Tributária', 'ICMS', true, false, false, false, false, false, false, true, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),203,'Isenção do ICMS no Simples Nacional para a faixa de Receita Bruta e com Cobrança do ICMS por Substituição Tributária', 'ICMS', true, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),300,'Imune', 'ICMS', true, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),400,'Não Tributada no Simples Nacional', 'ICMS', true, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),500,'ICMS cobrado anteriormente por Substituição Tributária ou por Antecipação', 'ICMS', true, false, false, false, false, false, false, true, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),900,'Outros', 'ICMS', true, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),0,'Entrada com Recuperação de Crédito', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),1,'Entrada Tributável com Alíquota Zero', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),2,'Entrada Isenta', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),3,'Entrada Não Tributada', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),4,'Entrada Imune', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),5,'Entrada com Suspensão', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),49,'Outras Entradas', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),50,'Saída Tributada', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),51,'Saída Tributável com Alíquota Zero', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),52,'Saída Isenta', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),53,'Saída Não Tributada', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),54,'Saída Imune', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),55,'Saída com Suspensão', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),99,'Outras Saídas', 'IPI', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),1,'Operação Tributável com Alíquota Básica', 'PIS', false, false, false, false, false, false, true, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),2,'Operação Tributável com Alíquota Diferenciada', 'PIS', false, false, false, false, false, false, true, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),3,'Operação Tributável com Alíquota por Unidade de Medida de Produto', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),4,'Operação Tributável Monofásica - Revenda a Alíquota Zero', 'PIS', false, false, false, false, false, false, true, false, true, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),5,'Operação Tributável por Substituição Tributária', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),6,'Operação Tributável a Alíquota Zero', 'PIS', false, false, false, false, false, false, true, false, true, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),7,'Operação Isenta da Contribuição', 'PIS', false, false, false, false, false, false, true, false, true, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),8,'Operação sem Incidência da Contribuição', 'PIS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),9,'Operação com Suspensão da Contribuição', 'PIS', false, false, false, false, false, false, true, false, true, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),49,'Outras Operações de Saída', 'PIS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),50,'Operação com Direito a Crédito - Vinculada a Receitas Tributadas no Mercado Interno', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),51,'Operação com Direito a Crédito - Vinculada a Receitas Não Tributadas no Mercado Interno', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),52,'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita de Exportação', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),53,'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não Tributadas no Mercado Interno', 'PIS', false, false, false, false, false, false, true, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),54,'Operação com Direito a Crédito - Vinculada a Receitas Tributadas no Mercado Interno e de Exportação', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),55,'Operação com Direito a Crédito - Vinculada a Receitas Não Tributadas no Mercado Interno e de Exportação', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),56,'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não Tributadas no Mercado Interno e de Exportação', 'PIS', false, false, false, false, false, false, true, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),60,'Crédito Presumido - Operação de Aquisição vinculada Exclusivamente a Receita Tributada no Mercado Interno', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),61,'Crédito Presumido - Operação de Aquisição vinculada Exclusivamente a Receita Não Tributada no Mercado Interno', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),62,'Crédito Presumido - Operação de Aquisição vinculada Exclusivamente a Receita de Exportação', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),63,'Crédito Presumido - Operação de Aquisição vinculada a Receitas Tributadas e Não Tributadas no Mercado Interno', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),64,'Crédito Presumido - Operação de Aquisição vinculada a Receitas Tributadas no Mercado Interno e de Exportação', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),65,'Crédito Presumido - Operação de Aquisição vinculada a Receitas Não Tributadas no Mercado Interno e de Exportação', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),66,'Crédito Presumido - Operação de Aquisição vinculada a Receitas Tributadas e Não Tributadas no Mercado Interno e de Exportação', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),67,'Crédito Presumido - Outras Operações', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),70,'Operação de Aquisição a Crédito', 'PIS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),71,'Operação de Aquisição com Isenção', 'PIS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),72,'Operação de Aquisição com Suspensão', 'PIS', false, false, false, false, false, false, true, false, true, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),73,'Operação de Aquisição de Alíquota Zero', 'PIS', false, false, false, false, false, false, true, false, true, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),74,'Operação de Aquisição sem Incidência da Contribuição', 'PIS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),75,'Operação de Aquisição por Substituição Tributária', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),98,'Outras Operações de Entrada', 'PIS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),99,'Outras Operações', 'PIS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),1,'Operação Tributável com Alíquota Básica', 'COFINS', false, false, false, false, false, false, true, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),2,'Operação Tributável com Alíquota Diferenciada', 'COFINS', false, false, false, false, false, false, true, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),3,'Operação Tributável com Alíquota por Unidade de Medida de Produto', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),4,'Operação Tributável Monofásica - Revenda a Alíquota Zero', 'COFINS', false, false, false, false, false, false, true, false, true, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),5,'Operação Tributável por Substituição Tributária', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),6,'Operação Tributável a Alíquota Zero', 'COFINS', false, false, false, false, false, false, true, false, true, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),7,'Operação Isenta da Contribuição', 'COFINS', false, false, false, false, false, false, true, false, true, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),8,'Operação sem Incidência da Contribuição', 'COFINS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),9,'Operação com Suspensão da Contribuição', 'COFINS', false, false, false, false, false, false, true, false, true, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),49,'Outras Operações de Saída', 'COFINS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),50,'Operação com Direito a Crédito - Vinculada a Receitas Tributadas no Mercado Interno', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),51,'Operação com Direito a Crédito - Vinculada a Receitas Não Tributadas no Mercado Interno', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),52,'Operação com Direito a Crédito - Vinculada Exclusivamente a Receita de Exportação', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),53,'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não Tributadas no Mercado Interno', 'COFINS', false, false, false, false, false, false, true, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),54,'Operação com Direito a Crédito - Vinculada a Receitas Tributadas no Mercado Interno e de Exportação', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),55,'Operação com Direito a Crédito - Vinculada a Receitas Não Tributadas no Mercado Interno e de Exportação', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),56,'Operação com Direito a Crédito - Vinculada a Receitas Tributadas e Não Tributadas no Mercado Interno e de Exportação', 'COFINS', false, false, false, false, false, false, true, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),60,'Crédito Presumido - Operação de Aquisição vinculada Exclusivamente a Receita Tributada no Mercado Interno', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),61,'Crédito Presumido - Operação de Aquisição vinculada Exclusivamente a Receita Não Tributada no Mercado Interno', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),62,'Crédito Presumido - Operação de Aquisição vinculada Exclusivamente a Receita de Exportação', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),63,'Crédito Presumido - Operação de Aquisição vinculada a Receitas Tributadas e Não Tributadas no Mercado Interno', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),64,'Crédito Presumido - Operação de Aquisição vinculada a Receitas Tributadas no Mercado Interno e de Exportação', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),65,'Crédito Presumido - Operação de Aquisição vinculada a Receitas Não Tributadas no Mercado Interno e de Exportação', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),66,'Crédito Presumido - Operação de Aquisição vinculada a Receitas Tributadas e Não Tributadas no Mercado Interno e de Exportação', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),67,'Crédito Presumido - Outras Operações', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),70,'Operação de Aquisição a Crédito', 'COFINS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),71,'Operação de Aquisição com Isenção', 'COFINS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),72,'Operação de Aquisição com Suspensão', 'COFINS', false, false, false, false, false, false, true, false, true, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),73,'Operação de Aquisição de Alíquota Zero', 'COFINS', false, false, false, false, false, false, true, false, true, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),74,'Operação de Aquisição sem Incidência da Contribuição', 'COFINS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),75,'Operação de Aquisição por Substituição Tributária', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),98,'Outras Operações de Entrada', 'COFINS', false, false, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp),
 (nextval('seq_situacao_tributaria'),99,'Outras Operações', 'COFINS', false, true, false, false, false, false, false, false, false, 1, NOW()::timestamp,1,NOW()::timestamp); 